version: '3.8'

services:
  # RDS Client for MySQL
  rds-client-mysql:
    build: .
    container_name: rds-client-mysql
    environment:
      - DB_ENGINE=mysql
      - DB_HOST=${MYSQL_DB_HOST:-mysql-rds.example.com}
      - DB_PORT=${MYSQL_DB_PORT:-3306}
      - DB_NAME=${MYSQL_DB_NAME:-testdb}
      - DB_USER=${MYSQL_DB_USER:-admin}
      - DB_PASSWORD=${MYSQL_DB_PASSWORD:-password123}
      - DB_CONNECTION_LIMIT=5
      - DB_TIMEOUT=10000
      - OPERATION_INTERVAL_MS=10000
      - SAMPLE_TABLE_NAME=mysql_users
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - mysql

  # RDS Client for PostgreSQL
  rds-client-postgresql:
    build: .
    container_name: rds-client-postgresql  
    environment:
      - DB_ENGINE=postgresql
      - DB_HOST=${POSTGRES_DB_HOST:-postgres-rds.example.com}
      - DB_PORT=${POSTGRES_DB_PORT:-5432}
      - DB_NAME=${POSTGRES_DB_NAME:-testdb}
      - DB_USER=${POSTGRES_DB_USER:-admin}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD:-password123}
      - DB_CONNECTION_LIMIT=5
      - DB_TIMEOUT=10000
      - OPERATION_INTERVAL_MS=10000
      - SAMPLE_TABLE_NAME=postgres_users
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - postgresql 