namespace: gcp-firebase-hosting-demo

# =============================================================================
# GCP Firebase Hosting Example
# =============================================================================
#
# This example demonstrates:
# 1. Enabling Firebase Hosting API
# 2. Creating a Firebase Hosting site
# 3. Creating a preview channel for staging deployments
# 4. Deploying content using Firebase CLI in a container (builder pattern)
#
# Prerequisites:
# - GCP provider configured in Monk with appropriate permissions
# - Firebase project (can be same as GCP project)
# - Site content as a blob
#
# Run with:
#   monk load gcp-firebase-hosting-demo/stack.yaml
#   monk run gcp-firebase-hosting-demo/hosting-app
#
# =============================================================================

# Process group to run everything together
hosting-app:
  defines: group
  members:
    - enable-apis
    - hosting-site
    - preview-channel
    - deploy-site

# =============================================================================
# Step 1: Enable Required APIs
# =============================================================================

enable-apis:
  defines: gcp/service-usage
  apis:
    - firebasehosting.googleapis.com
  services:
    apis-ready:
      protocol: custom

# =============================================================================
# Step 2: Create Firebase Hosting Site
# =============================================================================
# Creates a hosting site with default domain: {site-name}.web.app

hosting-site:
  defines: gcp/firebase-hosting-site
  name: monk-demo-site
  keep_on_delete: false

  labels:
    environment: demo
    managed-by: monk

  services:
    site:
      protocol: custom

  depends:
    wait-for:
      runnables:
        - gcp-firebase-hosting-demo/enable-apis
      timeout: 300

# =============================================================================
# Step 3: Create Preview Channel
# =============================================================================
# Preview channel for staging/testing before production
# URL: preview--{site-name}.web.app

preview-channel:
  defines: gcp/firebase-hosting-channel
  name: preview
  site: <- connection-target("site") entity-state get-member("site_id")
  ttl: "604800s" # 7 days
  retained_release_count: 3

  labels:
    purpose: staging
    auto-expire: "true"

  services:
    channel:
      protocol: custom

  connections:
    site:
      runnable: gcp-firebase-hosting-demo/hosting-site
      service: site

  depends:
    wait-for:
      runnables:
        - gcp-firebase-hosting-demo/hosting-site
      timeout: 300

# =============================================================================
# Step 4: Deploy Site Content (Builder Pattern)
# =============================================================================
# Uses the firebase/deploy builder template to deploy content from blob
#
# The firebase/deploy builder provides:
# - Firebase CLI pre-installed in the container
# - Configurable site-id, project, and deploy-dir
# - Pre-deploy hook for build steps
# - Optional channel deployment for previews
#
# Your blob should contain:
# 1. firebase.json (hosting configuration)
# 2. public/ directory with static files
#
# See firebase/hosting/deploy.yaml for full variable documentation.

deploy-site:
  inherits: firebase/deploy

  connections:
    site:
      runnable: gcp-firebase-hosting-demo/hosting-site
      service: site
    channel:
      runnable: gcp-firebase-hosting-demo/preview-channel
      service: channel

  depends:
    wait-for:
      runnables:
        - gcp-firebase-hosting-demo/hosting-site
        - gcp-firebase-hosting-demo/preview-channel
      timeout: 600

  containers:
    deploy:
      paths:
        # Mount site content from blob
        - <- `blobs://site-content:/home/node/app`

  variables:
    # Connect to the hosting site entity to get the site ID
    site-id: <- connection-target("site") entity-state get-member("site_id")
    # Optional: deploy to preview channel instead of production
    # channel: <- connection-target("channel") entity-state get-member("channel_id")
    # Pre-deploy hook (optional): add build steps here
    pre-deploy: <- `echo "Deploying Firebase Hosting site..."`
