namespace: gcp-firebase-hosting-demo

# =============================================================================
# GCP Firebase Hosting Example
# =============================================================================
#
# This example demonstrates:
# 1. Enabling Firebase Hosting API
# 2. Creating a Firebase Hosting site
# 3. Creating a preview channel for staging deployments
# 4. Deploying content using Firebase CLI in a container (builder pattern)
#
# Prerequisites:
# - GCP provider configured in Monk with appropriate permissions
# - Firebase project (can be same as GCP project)
# - Site content as a blob
#
# Run with:
#   monk load gcp-firebase-hosting-demo/stack.yaml
#   monk run gcp-firebase-hosting-demo/hosting-app
#
# =============================================================================

# Process group to run everything together
hosting-app:
  defines: process-group
  runnable-list:
    - enable-apis
    - hosting-site
    - preview-channel
    - deploy-site

# =============================================================================
# Step 1: Enable Required APIs
# =============================================================================

enable-apis:
  defines: gcp/service-usage
  apis:
    - firebasehosting.googleapis.com
  services:
    apis-ready:
      protocol: custom

# =============================================================================
# Step 2: Create Firebase Hosting Site
# =============================================================================
# Creates a hosting site with default domain: {site-name}.web.app

hosting-site:
  defines: gcp/firebase-hosting-site
  name: monk-demo-site
  keep_on_delete: false

  labels:
    environment: demo
    managed-by: monk

  services:
    site:
      protocol: https
      address: <- entity-state get-member("default_url") default("")

  depends:
    wait-for:
      runnables:
        - gcp-firebase-hosting-demo/enable-apis
      timeout: 300

# =============================================================================
# Step 3: Create Preview Channel
# =============================================================================
# Preview channel for staging/testing before production
# URL: preview--{site-name}.web.app

preview-channel:
  defines: gcp/firebase-hosting-channel
  name: preview
  site: <- connection-target("site") entity-state get-member("site_id")
  ttl: "604800s"  # 7 days
  retained_release_count: 3

  labels:
    purpose: staging
    auto-expire: "true"

  services:
    channel:
      protocol: https
      address: <- entity-state get-member("url") default("")

  connections:
    site:
      runnable: gcp-firebase-hosting-demo/hosting-site
      service: site

  depends:
    wait-for:
      runnables:
        - gcp-firebase-hosting-demo/hosting-site
      timeout: 300

# =============================================================================
# Step 4: Deploy Site Content (Builder Pattern)
# =============================================================================
# Uses Firebase CLI in a container to deploy content from blob
#
# NOTE: This requires:
# 1. A blob named "site-content" with your static files
# 2. A firebase.json in the blob root:
#    {
#      "hosting": {
#        "public": "public",
#        "ignore": ["firebase.json", "**/.*"]
#      }
#    }
# 3. Your static files in public/ directory
#
# Upload blob with: monk blob upload site-content ./my-site/

deploy-site:
  defines: runnable

  connections:
    site:
      runnable: gcp-firebase-hosting-demo/hosting-site
      service: site
    channel:
      runnable: gcp-firebase-hosting-demo/preview-channel
      service: channel

  depends:
    wait-for:
      runnables:
        - gcp-firebase-hosting-demo/hosting-site
        - gcp-firebase-hosting-demo/preview-channel
      timeout: 600

  variables:
    site_id:
      env: FIREBASE_SITE
      value: <- connection-target("site") entity-state get-member("site_id")
      type: string
    site_url:
      env: SITE_URL
      value: <- connection-target("site") entity-state get-member("default_url")
      type: string
    preview_url:
      env: PREVIEW_URL
      value: <- connection-target("channel") entity-state get-member("url")
      type: string
    gcp_project:
      env: GCP_PROJECT
      value: <- provider("gcp") get-member("project")
      type: string

  containers:
    deployer:
      image: node:20-slim
      paths:
        # Mount site content from blob
        - <- `blobs://site-content:/app/site`
      bash: |
        echo "========================================"
        echo "Firebase Hosting Deployment"
        echo "========================================"
        echo "Site ID: $FIREBASE_SITE"
        echo "Production URL: $SITE_URL"
        echo "Preview URL: $PREVIEW_URL"
        echo "Project: $GCP_PROJECT"
        echo ""

        # Install Firebase CLI
        echo "Installing Firebase CLI..."
        npm install -g firebase-tools

        cd /app/site

        # Create firebase.json if not exists
        if [ ! -f firebase.json ]; then
          echo "Creating default firebase.json..."
          cat > firebase.json << 'EOF'
        {
          "hosting": {
            "site": "${FIREBASE_SITE}",
            "public": "public",
            "ignore": [
              "firebase.json",
              "**/.*",
              "**/node_modules/**"
            ],
            "rewrites": [
              {
                "source": "**",
                "destination": "/index.html"
              }
            ]
          }
        }
        EOF
        fi

        # Create sample content if public/ doesn't exist
        if [ ! -d public ]; then
          echo "Creating sample content..."
          mkdir -p public
          cat > public/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <title>Monk Firebase Hosting Demo</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                   max-width: 800px; margin: 50px auto; padding: 20px; }
            h1 { color: #1a73e8; }
            .info { background: #f5f5f5; padding: 15px; border-radius: 8px; }
          </style>
        </head>
        <body>
          <h1>Hello from Firebase Hosting!</h1>
          <p>This site was deployed using Monk entities.</p>
          <div class="info">
            <h3>Deployment Info</h3>
            <p>Deployed at: <script>document.write(new Date().toISOString())</script></p>
          </div>
        </body>
        </html>
        EOF
        fi

        echo ""
        echo "Deploying to preview channel..."
        firebase deploy --only hosting:$FIREBASE_SITE \
          --project $GCP_PROJECT \
          --non-interactive \
          --message "Deployed via Monk"

        echo ""
        echo "========================================"
        echo "Deployment Complete!"
        echo "========================================"
        echo "Production: $SITE_URL"
        echo "Preview: $PREVIEW_URL"
        echo "========================================"
