namespace: service-bus

busnamespace:
  defines: service-bus/bus-namespace
  subscriptionId: "31b0b43d-0900-45b7-86a4-4cdd3cfd2550"
  resourceGroupName: "rg-service-bus"
  namespaceName: "monkservicebusnamespace"
  namespaceObject: |
   {
     "sku": {
       "name": "Standard",
       "tier": "Standard"
     },
     "location": "South Central US",
     "tags": {
       "tag1": "value1",
       "tag2": "value2"
     }
   }

busqueue:
  defines: service-bus/bus-queue
  subscriptionId: "31b0b43d-0900-45b7-86a4-4cdd3cfd2550"
  resourceGroupName: "rg-service-bus"
  namespaceName: "monkservicebusnamespace"
  queueName: "monkservicebusqueue"
  queueObject: |
   {
     "properties": {
       "enablePartitioning": true
     }
   }

bustopic:
  defines: service-bus/bus-topic
  subscriptionId: "31b0b43d-0900-45b7-86a4-4cdd3cfd2550"
  resourceGroupName: "rg-service-bus"
  namespaceName: "monkservicebusnamespace"
  topicName: "monkservicebustopic"
  topicObject: |
   {
     "properties": {
       "enableExpress": true
     }
   }

namespaceAuthorizationRule:
  defines: service-bus/bus-namespace-authRole
  subscriptionId: "31b0b43d-0900-45b7-86a4-4cdd3cfd2550"
  resourceGroupName: "rg-service-bus"
  namespaceName: "monkservicebusnamespace"
  authorizationRuleName: "namespace-auth-role"
  AuthorizationRuleObject: |
   {
     "properties": {
       "rights": [
         "Listen",
         "Send"
       ]
     }
   }

queueAuthorizationRule:
  defines: service-bus/bus-queue-authRole
  subscriptionId: "31b0b43d-0900-45b7-86a4-4cdd3cfd2550"
  resourceGroupName: "rg-service-bus"
  namespaceName: "monkservicebusnamespace"
  queueName: "monkservicebusqueue"
  authorizationRuleName: "queue-auth-role"
  AuthorizationRuleObject: |
   {
     "properties": {
       "rights": [
         "Listen",
         "Send"
       ]
     }
   }

topicAuthorizationRule:
  defines: service-bus/bus-topic-authRole
  subscriptionId: "31b0b43d-0900-45b7-86a4-4cdd3cfd2550"
  resourceGroupName: "rg-service-bus"
  namespaceName: "monkservicebusnamespace"
  topicName: "monkservicebustopic"
  authorizationRuleName: "topic-auth-role"
  AuthorizationRuleObject: |
   {
     "properties": {
       "rights": [
         "Listen",
         "Send"
       ]
     }
   }   

