namespace: service-bus

busnamespace:
  defines: service-bus/bus-namespace
  subscriptionId: "31b0b43d-0900-45b7-86a4-4cdd3cfd2550"
  resourceGroupName: "rg-service-bus"
  namespaceName: "monkservicebusnamespace"
  queueName: "monkservicebusqueue"
  topicName: "monktopic"
  namespaceObject: |
   {
     "sku": {
       "name": "Standard",
       "tier": "Standard"
     },
     "location": "South Central US",
     "tags": {
       "tag1": "value1",
       "tag2": "value2"
     }
   }
  queueObject: |
   {
     "properties": {
       "enablePartitioning": true
     }
   }
  topicObject: |
   {
     "properties": {
       "enableExpress": true
     }
   }
