namespace: gcp

cloud-sql:
  defines: process-group
  metadata:
    name: Google Cloud SQL
    description: |
      Fully managed relational database service for MySQL, PostgreSQL, and SQL Server with rich extension collections, configuration flags, and developer ecosystems.
    website: https://cloud.google.com/sql
    icon: https://symbols.getvecta.com/stencil_4/45_google-cloud-sql.35ca1b4c38.svg
    publisher: monk.io
    private: true
    tags: GCP, Cloud SQL, Entities
  runnable-list:
    - gcp/cloud-sql-instance
    - gcp/cloud-sql-database
    - gcp/cloud-sql-user
