namespace: objectstorage

storage:
  defines: objectstorage/storage-account
  subscriptionId: "31b0b43d-0900-45b7-86a4-4cdd3cfd2550"
  resourceGroupName: "rg-storage-account"
  accountName: "monkazurestorageaccount"
  # storageAccountObject: <<< ./storageaccountobject.json
  storageAccountObject: |
   {
       "sku": {
         "name": "Standard_GRS"
       },
       "kind": "Storage",
       "location": "eastus",
       "extendedLocation": {
         "type": "EdgeZone",
         "name": "losangeles001"
       },
       "properties": {
         "keyPolicy": {
           "keyExpirationPeriodInDays": 20
         },
         "sasPolicy": {
           "sasExpirationPeriod": "1.15:59:59",
           "expirationAction": "Log"
         },
         "isHnsEnabled": true,
         "isSftpEnabled": true,
         "allowBlobPublicAccess": false,
         "defaultToOAuthAuthentication": false,
         "minimumTlsVersion": "TLS1_2",
         "allowSharedKeyAccess": true,
         "routingPreference": {
           "routingChoice": "MicrosoftRouting",
           "publishMicrosoftEndpoints": true,
           "publishInternetEndpoints": true
         },
         "encryption": {
           "services": {
             "file": {
               "keyType": "Account",
               "enabled": true
             },
             "blob": {
               "keyType": "Account",
               "enabled": true
             }
           },
           "requireInfrastructureEncryption": false,
           "keySource": "Microsoft.Storage"
         }
       },
       "tags": {
         "key1": "value1",
         "key2": "value2"
       }
     }