namespace: firebase

firebase-db-instance:
  defines: entity
  metadata:
    name: Firebase Realtime Database
    description: |
      The Firebase Realtime Database is a cloud-hosted database. Data is stored as JSON and synchronized in realtime to every connected client.
    website: https://firebase.google.com/docs/database
    icon: https://symbols.getvecta.com/stencil_261/16_google-firebase.3828a6e3a4.svg
    publisher: monk.io
    tags: entities, realtime database, gcp, firebase
  schema:
    required: [ "name", "location", "project" ]
    name:
      type: string
    location: # one of us-central1, europe-west1, asia-southeast1
      type: string
    project: # firebase project
      type: string
    rules:
      type: string
  lifecycle:
    sync: <<< db-instance-sync.js
    # custom actions on instances
    disable: ""
    reenable: ""
    # working with security rules
    get-rules: ""
    set-rules: ""
    # actions to work with db data
    get: ""
    set: ""
    push: ""
    remove: ""
