namespace: gcp-redis-demo

# =============================================================================
# GCP Memorystore for Redis Client Example
# =============================================================================
#
# This example demonstrates:
# 1. Enabling the Redis API
# 2. Creating a Memorystore for Redis instance
# 3. Running a client application that performs Redis operations
#
# Prerequisites:
# - GCP provider configured in Monk with appropriate permissions
# - Project with billing enabled
# - VPC network configured (default VPC works for testing)
#
# IMPORTANT: Memorystore instances are accessible only from within the VPC.
# The client must run in a GCP environment with access to the VPC.
#
# Run with:
#   monk load examples/gcp-memorystore-redis-client/stack.yaml
#   monk run gcp-redis-demo/redis-app
#
# =============================================================================

# Process group to run everything together
redis-app:
  defines: group
  members:
    - enable-apis
    - redis-cache
    - redis-client

# =============================================================================
# Step 1: Enable Required APIs
# =============================================================================

enable-apis:
  defines: gcp/service-usage
  apis:
    - redis.googleapis.com
    - compute.googleapis.com

# =============================================================================
# Step 2: Create Memorystore for Redis Instance
# =============================================================================
# Creates a BASIC tier Redis instance (single node, best for dev/test)
# For production, use STANDARD_HA tier for automatic failover

redis-cache:
  defines: gcp/memorystore-redis
  # Instance ID - unique within the project and region
  name: monk-demo-redis
  
  # Region must have Memorystore support
  region: us-central1
  
  # BASIC: single node, no HA (cheaper, good for dev/test)
  # STANDARD_HA: with replica for automatic failover
  tier: BASIC
  
  # Memory size in GB (minimum 1GB)
  memory_size_gb: 1
  
  # Redis version
  redis_version: REDIS_7_0
  
  # Human-readable display name
  display_name: Monk Demo Redis Cache
  
  # Enable AUTH for password authentication
  # Note: AUTH string is auto-generated by GCP and not easily retrievable
  # For simpler access, set auth_enabled: false in dev environments
  auth_enabled: false
  
  # Redis configuration parameters
  # See: https://cloud.google.com/memorystore/docs/redis/supported-redis-configurations
  redis_configs:
    maxmemory-policy: volatile-lru
    notify-keyspace-events: Ex
  
  # RDB persistence for automatic snapshots
  persistence_config:
    persistence_mode: RDB
    rdb_snapshot_period: TWELVE_HOURS
  
  # Labels for organization
  labels:
    environment: demo
    managed-by: monk
  
  depends:
    wait-for:
      runnables:
        - gcp-redis-demo/enable-apis
      timeout: 300

# =============================================================================
# Step 3: Redis Client Application
# =============================================================================
# Runs a container that connects to Redis and performs operations
#
# IMPORTANT: This client must run in an environment that can reach the
# Memorystore instance (same VPC or with proper network peering).

redis-client:
  defines: runnable
  
  # Connect to Redis instance entity
  connections:
    redis:
      runnable: gcp-redis-demo/redis-cache
      service: data
  
  # Wait for Redis to be ready
  depends:
    wait-for:
      runnables:
        - gcp-redis-demo/redis-cache
      timeout: 1200  # Redis instances can take ~10-15 minutes to create
  
  # Environment variables from entity state
  variables:
    redis_host:
      env: REDIS_HOST
      value: <- connection-target("redis") entity-state get-member("host")
      type: string
    redis_port:
      env: REDIS_PORT
      value: <- connection-target("redis") entity-state get-member("port") default(6379) to-string
      type: string
  
  containers:
    client:
      # Using Redis official image with redis-cli
      image: redis:7-alpine
      bash: |
        #!/bin/sh
        set -e
        
        echo "========================================"
        echo "  Memorystore for Redis Client Demo"
        echo "========================================"
        echo ""
        echo "Redis Host: $REDIS_HOST"
        echo "Redis Port: $REDIS_PORT"
        echo ""
        
        # Function to run redis-cli commands
        redis_cmd() {
          redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" "$@"
        }
        
        # Wait for Redis to be accessible
        echo "Waiting for Redis connection..."
        max_attempts=30
        attempt=1
        while ! redis_cmd PING > /dev/null 2>&1; do
          if [ $attempt -ge $max_attempts ]; then
            echo "ERROR: Could not connect to Redis after $max_attempts attempts"
            echo "Note: Memorystore is only accessible from within the VPC."
            echo "Ensure this client is running in a GCP environment with VPC access."
            exit 1
          fi
          echo "  Attempt $attempt/$max_attempts - waiting..."
          sleep 5
          attempt=$((attempt + 1))
        done
        
        echo "Connected to Redis!"
        echo ""
        
        # ===== Basic Operations =====
        echo "--- Basic String Operations ---"
        
        # SET and GET
        echo "SET greeting 'Hello from Monk!'"
        redis_cmd SET greeting "Hello from Monk!"
        
        echo "GET greeting:"
        redis_cmd GET greeting
        echo ""
        
        # SET with expiration
        echo "SETEX temp_key 60 'This expires in 60 seconds'"
        redis_cmd SETEX temp_key 60 "This expires in 60 seconds"
        
        echo "TTL temp_key:"
        redis_cmd TTL temp_key
        echo ""
        
        # ===== Counter Operations =====
        echo "--- Counter Operations ---"
        
        redis_cmd SET visit_counter 0
        echo "Incrementing counter 5 times:"
        for i in 1 2 3 4 5; do
          result=$(redis_cmd INCR visit_counter)
          echo "  INCR visit_counter = $result"
        done
        echo ""
        
        # ===== Hash Operations =====
        echo "--- Hash Operations (User Profile) ---"
        
        echo "Creating user profile hash..."
        redis_cmd HSET user:1001 name "Alice" email "alice@example.com" visits 0
        
        echo "HGETALL user:1001:"
        redis_cmd HGETALL user:1001
        
        echo "HINCRBY user:1001 visits 1:"
        redis_cmd HINCRBY user:1001 visits 1
        
        echo "HGET user:1001 visits:"
        redis_cmd HGET user:1001 visits
        echo ""
        
        # ===== List Operations =====
        echo "--- List Operations (Task Queue) ---"
        
        echo "Adding tasks to queue..."
        redis_cmd RPUSH task_queue "task:process_image"
        redis_cmd RPUSH task_queue "task:send_email"
        redis_cmd RPUSH task_queue "task:generate_report"
        
        echo "LRANGE task_queue 0 -1 (all tasks):"
        redis_cmd LRANGE task_queue 0 -1
        
        echo "LPOP task_queue (get next task):"
        redis_cmd LPOP task_queue
        
        echo "Remaining tasks:"
        redis_cmd LRANGE task_queue 0 -1
        echo ""
        
        # ===== Set Operations =====
        echo "--- Set Operations (Tags) ---"
        
        echo "Adding tags to article sets..."
        redis_cmd SADD article:100:tags "technology" "cloud" "redis" "caching"
        redis_cmd SADD article:101:tags "technology" "database" "nosql"
        
        echo "SMEMBERS article:100:tags:"
        redis_cmd SMEMBERS article:100:tags
        
        echo "SINTER article:100:tags article:101:tags (common tags):"
        redis_cmd SINTER article:100:tags article:101:tags
        echo ""
        
        # ===== Sorted Set Operations =====
        echo "--- Sorted Set Operations (Leaderboard) ---"
        
        echo "Creating game leaderboard..."
        redis_cmd ZADD leaderboard 1500 "player:alice"
        redis_cmd ZADD leaderboard 2200 "player:bob"
        redis_cmd ZADD leaderboard 1800 "player:charlie"
        redis_cmd ZADD leaderboard 3000 "player:diana"
        
        echo "ZREVRANGE leaderboard 0 -1 WITHSCORES (top players):"
        redis_cmd ZREVRANGE leaderboard 0 -1 WITHSCORES
        
        echo "ZRANK leaderboard player:charlie (rank, 0-indexed):"
        redis_cmd ZRANK leaderboard player:charlie
        echo ""
        
        # ===== Server Info =====
        echo "--- Server Information ---"
        echo "INFO server (excerpt):"
        redis_cmd INFO server | head -15
        echo ""
        
        echo "INFO memory (excerpt):"
        redis_cmd INFO memory | head -10
        echo ""
        
        # ===== Pub/Sub Demo =====
        echo "--- Pub/Sub Demo ---"
        echo "Publishing message to 'notifications' channel..."
        redis_cmd PUBLISH notifications "Hello subscribers! Demo message from Monk."
        echo "(Note: No subscribers active, message count shows 0)"
        echo ""
        
        # ===== Cleanup Demo Data =====
        echo "--- Cleanup ---"
        echo "Deleting demo keys..."
        redis_cmd DEL greeting temp_key visit_counter user:1001 task_queue \
          article:100:tags article:101:tags leaderboard
        echo "Cleanup complete!"
        echo ""
        
        # ===== Continuous Monitoring =====
        echo "========================================"
        echo "Demo complete! Starting monitoring loop..."
        echo "========================================"
        echo ""
        
        counter=1
        while true; do
          timestamp=$(date '+%Y-%m-%d %H:%M:%S')
          echo "[$timestamp] Ping #$counter"
          
          # Store a timestamped key
          redis_cmd SET "heartbeat:$counter" "$timestamp" EX 300
          
          # Check memory usage
          memory=$(redis_cmd INFO memory | grep used_memory_human | cut -d: -f2 | tr -d '\r')
          echo "  Memory usage: $memory"
          
          # Show recent heartbeats
          keys=$(redis_cmd KEYS "heartbeat:*" | wc -l)
          echo "  Active heartbeat keys: $keys"
          
          counter=$((counter + 1))
          echo "  Sleeping 30 seconds..."
          echo ""
          sleep 30
        done
