namespace: netlify

site:
  defines: entity
  permitted-secrets:
    default-netlify-pat: true
  schema:
    required: ["name"]
    secret_ref:
      type: string
      default: default-netlify-pat
    name:
      type: string
    team_slug:
      type: string
    password:
      type: string
    custom_domain:
      type: string
    force_ssl:
      type: bool
  lifecycle:
    sync: <<< site-sync.js
  checks:
    readiness:
      period: 10
      initialDelay: 2
