name: Build and Commit Dist

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build modules
      run: |
        ./build.sh

    - name: Check for dist changes
      id: check-changes
      run: |
        echo "### Full git status before check ###"
        git status
        echo
        echo "### Porcelain status for dist/ ###"
        git status --porcelain dist/
        echo "------------------------------------"

        if [ -z "$(git status --porcelain dist/)" ]; then
          echo "Result: No changes detected in dist/."
          echo "no-changes=true" >> $GITHUB_OUTPUT
        else
          echo "Result: Changes detected in dist/."
          echo "no-changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push dist changes
      if: steps.check-changes.outputs.no-changes == 'false'
      run: |
        echo "Attempting to commit changes..."
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/
        echo
        echo "### Git status after add, before commit ###"
        git status
        echo "-------------------------------------------"
        git commit -m "Build: Update dist files [skip ci]"
        git push 