namespace: neon

project:
  defines: entity
  schema:
    required: ["name", "secret_ref"]
    name:
      type: string
    secret_ref:
      type: string
    allowed_ips:
      type: array
      items:
        type: string
    pg_version:
      default: 21
      enum:
        - 14
        - 15
        - 16
        - 17
    region_id:
      default: aws-us-east-2
      enum:
        - aws-us-east-1
        - aws-us-east-2
        - aws-us-west-2
        - aws-eu-central-1
        - aws-eu-west-2
        - aws-ap-southeast-1
        - aws-ap-southeast-2
        - aws-sa-east-1
        - azure-eastus2
        - azure-westus3
        - azure-gwc
  lifecycle:
    sync: <<< project-sync.js
  checks:
    readiness:
      period: 10
      initialDelay: 2
